services:
  next:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev